<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Subcategory;
use App\Models\Tag;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Durian
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'durian',
                'name' => 'Bibit Durian Musang King',
                'scientific_name' => 'Durio zibethinus',
                'description' => 'Bibit durian Musang King unggulan dari Malaysia. Buah berdaging tebal, tekstur creamy, dan rasa manis legit yang khas. Cepat berbuah dalam 3-4 tahun.',
                'care_instructions' => '1. Tanam di lokasi dengan sinar matahari penuh\n2. Gunakan media tanam yang drainase baik\n3. Siram secara teratur, hindari genangan air\n4. Pupuk organic setiap 3 bulan\n5. Pangkas cabang yang tidak produktif',
                'price' => 120000,
                'original_price' => 150000,
                'size' => '80-100 cm',
                'weight' => '1.5-2 kg',
                'age_months' => 12,
                'origin' => 'Malaysia',
                'tags' => ['Bibit Unggul', 'Cepat Berbuah', 'Premium'],
                'is_bestseller' => true,
                'rating' => 4.9,
                'review_count' => 320,
                'sold_count' => 520,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'durian',
                'name' => 'Bibit Durian Bawor',
                'scientific_name' => 'Durio zibethinus',
                'description' => 'Bibit durian Bawor (Banyumas Wonder) asli Indonesia. Buah besar dengan daging tebal dan rasa manis creamy. Cocok untuk dataran rendah hingga menengah.',
                'care_instructions' => '1. Tanam di tanah gembur dengan pH 6-7\n2. Sinar matahari minimal 6 jam sehari\n3. Siram 2-3 kali seminggu\n4. Beri pupuk NPK seimbang\n5. Lakukan pemangkasan formasi',
                'price' => 85000,
                'size' => '70-90 cm',
                'weight' => '1.2-1.8 kg',
                'age_months' => 10,
                'origin' => 'Banyumas, Indonesia',
                'tags' => ['Bibit Unggul', 'Cocok Dataran Rendah'],
                'rating' => 4.8,
                'review_count' => 210,
                'sold_count' => 380,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'durian',
                'name' => 'Bibit Durian Duri Hitam',
                'scientific_name' => 'Durio zibethinus',
                'description' => 'Bibit durian Duri Hitam dengan ciri khas daging berwarna kekuningan kemerahan. Rasa manis dengan sedikit pahit yang khas.',
                'care_instructions' => '1. Tanam di lokasi teduh sebagian\n2. Media tanam campuran tanah, kompos, dan pasir\n3. Jaga kelembaban tanah\n4. Beri pupuk organic secara rutin\n5. Lindungi dari hama tikus dan tupai',
                'price' => 95000,
                'size' => '75-95 cm',
                'weight' => '1.3-1.9 kg',
                'age_months' => 11,
                'origin' => 'Thailand',
                'tags' => ['Tanaman Langka', 'Premium'],
                'rating' => 4.7,
                'review_count' => 150,
                'sold_count' => 220,
            ],
            
            // Alpukat
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'alpukat',
                'name' => 'Bibit Alpukat Aligator',
                'scientific_name' => 'Persea americana',
                'description' => 'Bibit alpukat Aligator dengan buah berbentuk seperti buaya, kulit hijau mengkilap, daging creamy kuning kehijauan. Rasa gurih dan nutrisi tinggi.',
                'care_instructions' => '1. Tanam di lokasi dengan cahaya terang\n2. Hindari angin kencang\n3. Siram secara teratur jangan sampai kering\n4. Pupuk dengan pupuk kandang atau kompos\n5. Pangkas untuk membentuk kanopi',
                'price' => 45000,
                'original_price' => 55000,
                'size' => '60-80 cm',
                'weight' => '0.8-1.2 kg',
                'age_months' => 8,
                'origin' => 'Florida, USA',
                'tags' => ['Unggulan', 'Bibit Unggul', 'Cepat Berbuah'],
                'is_bestseller' => true,
                'rating' => 4.8,
                'review_count' => 280,
                'sold_count' => 450,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'alpukat',
                'name' => 'Bibit Alpukat Red Vietnam',
                'scientific_name' => 'Persea americana',
                'description' => 'Bibit alpukat Red Vietnam dengan kulit merah saat matang. Daging creamy dan rasa manis gurih. Varietas langka dan eksotis.',
                'care_instructions' => '1. Tanam di lokasi teduh sebagian saat masih kecil\n2. Pindahkan ke sinar penuh setelah dewasa\n3. Siram teratur\n4. Beri pupuk phosphor tinggi saat berbunga\n5. Jaga kelembaban udara',
                'price' => 65000,
                'size' => '65-85 cm',
                'weight' => '0.9-1.4 kg',
                'age_months' => 9,
                'origin' => 'Vietnam',
                'tags' => ['Tanaman Langka', 'Premium', 'New Arrival'],
                'is_new_arrival' => true,
                'rating' => 4.9,
                'review_count' => 95,
                'sold_count' => 180,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'alpukat',
                'name' => 'Bibit Alpukat Mikel (Miki)',
                'scientific_name' => 'Persea americana',
                'description' => 'Bibit alpukat Mikel unggulan lokal dengan buah besar 800gr-1.2kg. Kulit hijau mengkilap, daging creamy kuning cerah.',
                'care_instructions' => '1. Tanam di tanah gembur dan subur\n2. Sinar matahari 6-8 jam sehari\n3. Siram 2 kali seminggu\n4. Pupuk organic bulanan\n5. Pangkas untuk merangsang percabangan',
                'price' => 35000,
                'size' => '50-70 cm',
                'weight' => '0.6-1.0 kg',
                'age_months' => 7,
                'origin' => 'Indonesia',
                'tags' => ['Cocok Dataran Rendah', 'Organic'],
                'rating' => 4.6,
                'review_count' => 175,
                'sold_count' => 290,
            ],
            
            // Mangga
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'mangga',
                'name' => 'Bibit Mangga Miyazaki',
                'scientific_name' => 'Mangifera indica',
                'description' => 'Bibit mangga Miyazaki premium dari Jepang. Buah berwarna merah cerah saat matang, daging orange juicy, rasa manis sempurna. Dinobatkan sebagai mangga termahal di dunia.',
                'care_instructions' => '1. Tanam di greenhouse atau polybag besar\n2. Kontrol suhu 25-30°C optimal\n3. Siram dengan sistem drip irrigation\n4. Pupuk cair berkualitas tinggi\n5. Bungkus buah saat berkembang',
                'price' => 65000,
                'original_price' => 80000,
                'size' => '70-90 cm',
                'weight' => '1.0-1.5 kg',
                'age_months' => 10,
                'origin' => 'Jepang',
                'tags' => ['Premium', 'Tanaman Langka', 'Unggulan'],
                'is_bestseller' => true,
                'is_featured' => true,
                'rating' => 4.9,
                'review_count' => 250,
                'sold_count' => 360,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'mangga',
                'name' => 'Bibit Mangga Harum Manis',
                'scientific_name' => 'Mangifera indica',
                'description' => 'Bibit mangga Harum Manis klasik Indonesia. Aroma harum khas, daging tebal tidak berserat, rasa manis legit. Paling dicari untuk konsumsi segar.',
                'care_instructions' => '1. Tanam di lokasi panas dan kering\n2. Siram minimal, tahan kekeringan\n3. Pupuk organic setiap 2 bulan\n4. Pangkas untuk membentuk kanopi rendah\n5. Panen saat setengah matang',
                'price' => 28000,
                'size' => '55-75 cm',
                'weight' => '0.7-1.1 kg',
                'age_months' => 8,
                'origin' => 'Probolinggo, Indonesia',
                'tags' => ['Cepat Berbuah', 'Best Seller', 'Organic'],
                'rating' => 4.7,
                'review_count' => 420,
                'sold_count' => 680,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'mangga',
                'name' => 'Bibit Mangga Red Emperor',
                'scientific_name' => 'Mangifera indica',
                'description' => 'Bibit mangga Red Emperor dengan kulit merah keunguan saat matang. Buah besar 600-800gr, daging orange kemerahan, rasa manis dengan aroma rose.',
                'care_instructions' => '1. Tanam di lokasi terbuka sinar penuh\n2. Media tanam drainase baik\n3. Siram teratur saat musim kemarau\n4. Pupuk NPK seimbang\n5. Jaga jarak tanam 8x8 meter',
                'price' => 38000,
                'size' => '60-80 cm',
                'weight' => '0.8-1.2 kg',
                'age_months' => 9,
                'origin' => 'Australia',
                'tags' => ['New Arrival', 'Premium'],
                'is_new_arrival' => true,
                'rating' => 4.8,
                'review_count' => 120,
                'sold_count' => 195,
            ],
            
            // Jeruk
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'jeruk',
                'name' => 'Bibit Jeruk Lemon',
                'scientific_name' => 'Citrus limon',
                'description' => 'Bibit jeruk lemon premium untuk kebutuhan rumah tangga dan komersial. Buah besar, kulit kuning cerah, jus asam segar. Cocok untuk dataran tinggi.',
                'care_instructions' => '1. Tanam di dataran tinggi 800-1500 mdpl\n2. Sinar matahari penuh minimal 6 jam\n3. Siram teratur jangan sampai kering\n4. Pupuk dengan kandungan nitrogen tinggi\n5. Pangkas cabang yang sakit atau tua',
                'price' => 30000,
                'original_price' => 38000,
                'size' => '50-70 cm',
                'weight' => '0.6-1.0 kg',
                'age_months' => 8,
                'origin' => 'California, USA',
                'tags' => ['Cocok Dataran Rendah', 'Cepat Berbuah', 'Best Seller'],
                'is_bestseller' => true,
                'rating' => 4.7,
                'review_count' => 190,
                'sold_count' => 350,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'jeruk',
                'name' => 'Bibit Jeruk Dekopon',
                'scientific_name' => 'Citrus reticulata',
                'description' => 'Bibit jeruk Dekopon (Shiranui) dari Jepang. Buah besar dengan kulit berbintik-bintik, daging manis tanpa biji, mudah dikupas.',
                'care_instructions' => '1. Tanam di lokasi dengan sinar terang\n2. Hindari angin kencang\n3. Siram secara teratur\n4. Beri pupuk mikro nutrisi\n5. Bungkus buah saat berkembang',
                'price' => 42000,
                'size' => '55-75 cm',
                'weight' => '0.7-1.1 kg',
                'age_months' => 9,
                'origin' => 'Jepang',
                'tags' => ['Premium', 'New Arrival'],
                'is_new_arrival' => true,
                'rating' => 4.8,
                'review_count' => 85,
                'sold_count' => 145,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'jeruk',
                'name' => 'Bibit Jeruk Keprok',
                'scientific_name' => 'Citrus reticulata',
                'description' => 'Bibit jeruk keprok unggulan lokal. Buah sedang, kulit orange cerah, daging manis segar, mudah dikupas. Cepat berbuah dan produktif.',
                'care_instructions' => '1. Tanam di berbagai ketinggian\n2. Sinar matahari penuh\n3. Siram teratur\n4. Pupuk organic dan NPK\n5. Kontrol hama kutu putih',
                'price' => 25000,
                'size' => '45-65 cm',
                'weight' => '0.5-0.9 kg',
                'age_months' => 7,
                'origin' => 'Indonesia',
                'tags' => ['Cepat Berbuah', 'Organic'],
                'rating' => 4.6,
                'review_count' => 230,
                'sold_count' => 410,
            ],
            
            // Kelengkeng
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'kelengkeng',
                'name' => 'Bibit Kelengkeng New Crystal',
                'scientific_name' => 'Dimocarpus longan',
                'description' => 'Bibit kelengkeng New Crystal unggulan Thailand. Buah besar seperti permata, daging tebal transparan, rasa manis krimi. Produktivitas tinggi.',
                'care_instructions' => '1. Tanam di lokasi panas dan kering\n2. Siram minimal, tahan kekeringan\n3. Pupuk organic setiap 3 bulan\n4. Pangkas untuk merangsang bunga\n5. Beri stimulan bunga saat musim kering',
                'price' => 35000,
                'original_price' => 45000,
                'size' => '60-80 cm',
                'weight' => '0.8-1.2 kg',
                'age_months' => 10,
                'origin' => 'Thailand',
                'tags' => ['Cepat Berbuah', 'Best Seller', 'Unggulan'],
                'is_bestseller' => true,
                'rating' => 4.8,
                'review_count' => 210,
                'sold_count' => 385,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'kelengkeng',
                'name' => 'Bibit Kelengkeng Itoh',
                'scientific_name' => 'Dimocarpus longan',
                'description' => 'Bibit kelengkeng Itoh dari Jepang. Buah jumbo, daging super tebal, rasa manis dengan aroma floral. Varietas premium langka.',
                'care_instructions' => '1. Tanam di greenhouse untuk hasil optimal\n2. Kontrol suhu dan kelembaban\n3. Siram dengan sistem drip\n4. Pupuk cair berkualitas\n5. Beri naungan saat panas ekstrem',
                'price' => 55000,
                'size' => '65-85 cm',
                'weight' => '0.9-1.4 kg',
                'age_months' => 11,
                'origin' => 'Jepang',
                'tags' => ['Premium', 'Tanaman Langka'],
                'rating' => 4.9,
                'review_count' => 75,
                'sold_count' => 120,
            ],
            
            // Tanaman Hias
            [
                'category_slug' => 'tanaman-hias-bunga',
                'subcategory_slug' => 'pucuk-merah',
                'name' => 'Bibit Pucuk Merah Premium',
                'scientific_name' => 'Syzygium myrtifolium',
                'description' => 'Bibit Pucuk Merah dengan daun merah menyala yang memukau. Tanaman hias premium untuk taman dan pekarangan. Tumbuh cepat dan mudah dirawat.',
                'care_instructions' => '1. Tanam di lokasi sinar penuh untuk warna optimal\n2. Media tanam gembur dan subur\n3. Siram teratur\n4. Pupuk NPK seimbang\n5. Pangkas untuk membentuk',
                'price' => 25000,
                'original_price' => 32000,
                'size' => '40-60 cm',
                'weight' => '0.4-0.8 kg',
                'age_months' => 6,
                'origin' => 'Indonesia',
                'tags' => ['Tanaman Langka', 'Premium', 'Cepat Berbuah'],
                'is_featured' => true,
                'rating' => 4.7,
                'review_count' => 165,
                'sold_count' => 280,
            ],
            [
                'category_slug' => 'tanaman-hias-bunga',
                'subcategory_slug' => 'ketapang-kencana',
                'name' => 'Bibit Ketapang Kencana',
                'scientific_name' => 'Terminalia mantaly',
                'description' => 'Bibit Ketapang Kencana dengan daun merah yang menawan. Bentuk kanopi yang indah, cocok untuk shade tree atau hiasan taman.',
                'care_instructions' => '1. Tanam di lokasi terbuka\n2. Tahan angin dan polusi\n3. Siram saat masih muda\n4. Minimal perawatan setelah dewasa\n5. Pangkas cabang bawah untuk bentuk',
                'price' => 35000,
                'size' => '80-120 cm',
                'weight' => '1.0-2.0 kg',
                'age_months' => 12,
                'origin' => 'Madagaskar',
                'tags' => ['Cocok Dataran Rendah', 'Organic'],
                'rating' => 4.6,
                'review_count' => 95,
                'sold_count' => 175,
            ],
            [
                'category_slug' => 'tanaman-hias-bunga',
                'subcategory_slug' => 'tabebuya',
                'name' => 'Bibit Tabebuya Pink',
                'scientific_name' => 'Handroanthus impetiginosus',
                'description' => 'Bibit Tabebuya dengan bunga pink spektakuler. Pohon besar yang menghiasi jalan dengan bunga lebat. Daya tahan tinggi dan cantik.',
                'care_instructions' => '1. Tanam di lokasi terbuka luas\n2. Sinar matahari penuh\n3. Siram saat masih muda\n4. Tahan kekeringan setelah dewasa\n5. Minimal perawatan',
                'price' => 45000,
                'size' => '100-150 cm',
                'weight' => '1.5-2.5 kg',
                'age_months' => 14,
                'origin' => 'Amerika Selatan',
                'tags' => ['Tanaman Langka', 'Premium'],
                'rating' => 4.8,
                'review_count' => 80,
                'sold_count' => 140,
            ],
            
            // Kopi
            [
                'category_slug' => 'tanaman-perkebunan',
                'subcategory_slug' => 'kopi',
                'name' => 'Bibit Kopi Arabika Gayo',
                'scientific_name' => 'Coffea arabica',
                'description' => 'Bibit kopi Arabika Gayo unggulan Aceh. Cita rasa kopi premium dunia dengan notes floral dan chocolate. Cocok dataran tinggi 1200-1600 mdpl.',
                'care_instructions' => '1. Tanam di dataran tinggi 1200-1600 mdpl\n2. Naungan 50-70% saat muda\n3. Siram teratur\n4. Pupuk organic berkualitas\n5. Pohon pelindung yang sesuai',
                'price' => 18000,
                'original_price' => 25000,
                'size' => '30-50 cm',
                'weight' => '0.3-0.6 kg',
                'age_months' => 5,
                'origin' => 'Aceh, Indonesia',
                'tags' => ['Organic', 'Premium', 'Cocok Dataran Rendah'],
                'is_featured' => true,
                'rating' => 4.9,
                'review_count' => 145,
                'sold_count' => 310,
            ],
            [
                'category_slug' => 'tanaman-perkebunan',
                'subcategory_slug' => 'kopi',
                'name' => 'Bibit Kopi Robusta',
                'scientific_name' => 'Coffea canephora',
                'description' => 'Bibit kopi Robusta untuk produksi komersial. Tahan penyakit, produktivitas tinggi, rasa strong dengan caffeine tinggi.',
                'care_instructions' => '1. Tanam di dataran rendah-menengah\n2. Sinar matahari penuh\n3. Siram teratur\n4. Pupuk NPK lengkap\n5. Kontrol hama penggerek buah',
                'price' => 12000,
                'size' => '25-45 cm',
                'weight' => '0.25-0.5 kg',
                'age_months' => 4,
                'origin' => 'Indonesia',
                'tags' => ['Cocok Dataran Rendah', 'Best Seller'],
                'rating' => 4.6,
                'review_count' => 200,
                'sold_count' => 520,
            ],
            
            // Kelapa
            [
                'category_slug' => 'tanaman-perkebunan',
                'subcategory_slug' => 'kelapa',
                'name' => 'Bibit Kelapa Genjah Entog',
                'scientific_name' => 'Cocos nucifera',
                'description' => 'Bibit kelapa Genjah Entog unggulan. Berbuah dalam 3-4 tahun, produktivitas tinggi, air kelapa manis, daging tebal.',
                'care_instructions' => '1. Tanam di lokasi terbuka pantai\n2. Media tanam pasir berhumus\n3. Siram teratur saat muda\n4. Tahan kekeringan setelah dewasa\n5. Minimal perawatan',
                'price' => 35000,
                'original_price' => 45000,
                'size' => '60-90 cm',
                'weight' => '3-5 kg',
                'age_months' => 8,
                'origin' => 'Indonesia',
                'tags' => ['Cepat Berbuah', 'Best Seller', 'Unggulan'],
                'is_bestseller' => true,
                'rating' => 4.8,
                'review_count' => 280,
                'sold_count' => 450,
            ],
            [
                'category_slug' => 'tanaman-perkebunan',
                'subcategory_slug' => 'kelapa',
                'name' => 'Bibit Kelapa Kopyor',
                'scientific_name' => 'Cocos nucifera',
                'description' => 'Bibit kelapa Kopyor langka dengan daging berwarna putih krem dan tekstur seperti jelly. Rasa manis unik, nilai jual tinggi.',
                'care_instructions' => '1. Tanam di lokasi dengan drainase baik\n2. Sinar matahari penuh\n3. Siram teratur\n4. Media tanam subur\n5. Pelindung dari angin kencang',
                'price' => 75000,
                'size' => '70-100 cm',
                'weight' => '4-6 kg',
                'age_months' => 10,
                'origin' => 'Indonesia',
                'tags' => ['Tanaman Langka', 'Premium'],
                'rating' => 4.9,
                'review_count' => 120,
                'sold_count' => 195,
            ],
            
            // Sawo
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'sawo',
                'name' => 'Bibit Sawo Manila',
                'scientific_name' => 'Manilkara zapota',
                'description' => 'Bibit sawo Manila dengan buah besar, daging lembut manis, biji kecil. Produktivitas tinggi dan tahan penyakit.',
                'care_instructions' => '1. Tanam di lokasi panas dan kering\n2. Tahan kekeringan baik\n3. Siram minimal\n4. Pupuk organic\n5. Pangkas untuk bentuk kanopi',
                'price' => 25000,
                'size' => '50-70 cm',
                'weight' => '0.7-1.1 kg',
                'age_months' => 8,
                'origin' => 'Filipina',
                'tags' => ['Cocok Dataran Rendah', 'Cepat Berbuah'],
                'rating' => 4.6,
                'review_count' => 140,
                'sold_count' => 265,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'sawo',
                'name' => 'Bibit Sawo Jumbo',
                'scientific_name' => 'Manilkara zapota',
                'description' => 'Bibit sawo Jumbo dengan buah super besar 400-600gr. Daging tebal manis, produktivitas tinggi, cocok untuk komersial.',
                'care_instructions' => '1. Tanam di tanah gembur\n2. Sinar matahari penuh\n3. Siram teratur saat berbuah\n4. Pupuk lengkap\n5. Jarak tanam 7x7 meter',
                'price' => 32000,
                'size' => '55-75 cm',
                'weight' => '0.8-1.3 kg',
                'age_months' => 9,
                'origin' => 'Thailand',
                'tags' => ['Unggulan', 'Premium'],
                'rating' => 4.7,
                'review_count' => 95,
                'sold_count' => 180,
            ],
            
            // Jeruk Bali & Pamelo
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'jeruk',
                'name' => 'Bibit Jeruk Bali',
                'scientific_name' => 'Citrus maxima',
                'description' => 'Bibit jeruk Bali (Bali Pomelo) dengan buah raksasa 2-4kg. Daging putih krem manis, sedikit asam, aroma harum.',
                'care_instructions' => '1. Tanam di lokasi terbuka luas\n2. Sinar matahari penuh\n3. Siram teratur\n4. Pupuk organic dan NPK\n5. Jarak tanam besar 10x10 meter',
                'price' => 35000,
                'size' => '60-85 cm',
                'weight' => '0.9-1.4 kg',
                'age_months' => 10,
                'origin' => 'Bali, Indonesia',
                'tags' => ['Premium', 'Unggulan'],
                'rating' => 4.8,
                'review_count' => 110,
                'sold_count' => 205,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'jeruk',
                'name' => 'Bibit Jeruk Pamelo Merah',
                'scientific_name' => 'Citrus maxima',
                'description' => 'Bibit jeruk Pamelo Merah eksotis dengan daging pink kemerahan. Rasa manis dengan sedikit asam segar, tampilan menarik.',
                'care_instructions' => '1. Tanam di lokasi sinar penuh\n2. Media tanam drainase baik\n3. Siram teratur\n4. Pupuk cair bulanan\n5. Bungkus buah untuk proteksi',
                'price' => 40000,
                'size' => '65-90 cm',
                'weight' => '1.0-1.6 kg',
                'age_months' => 11,
                'origin' => 'Thailand',
                'tags' => ['Tanaman Langka', 'Premium', 'New Arrival'],
                'is_new_arrival' => true,
                'rating' => 4.9,
                'review_count' => 65,
                'sold_count' => 115,
            ],
            
            // Jambu
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'jambu',
                'name' => 'Bibit Jambu Kristal',
                'scientific_name' => 'Psidium guajava',
                'description' => 'Bibit jambu Kristal dengan buah besar, daging putih transparan kristal, biji sangat sedikit, rasa manis krimi.',
                'care_instructions' => '1. Tanam di lokasi terbuka\n2. Sinar matahari penuh\n3. Siram teratur\n4. Pupuk organic\n5. Pangkas untuk merangsang buah',
                'price' => 22000,
                'original_price' => 28000,
                'size' => '45-65 cm',
                'weight' => '0.5-0.9 kg',
                'age_months' => 7,
                'origin' => 'Taiwan',
                'tags' => ['Cepat Berbuah', 'Best Seller'],
                'is_bestseller' => true,
                'rating' => 4.7,
                'review_count' => 180,
                'sold_count' => 340,
            ],
            [
                'category_slug' => 'buah-bibit-buah',
                'subcategory_slug' => 'jambu',
                'name' => 'Bibit Jambu Merah Deli',
                'scientific_name' => 'Psidium guajava',
                'description' => 'Bibit jambu Merah Deli dengan buah berwarna merah cerah saat matang. Daging merah muda, rasa manis asam segar.',
                'care_instructions' => '1. Tanam di tanah gembur\n2. Sinar matahari penuh\n3. Siram teratur\n4. Pupuk NPK\n5. Kontrol hama kutu putih',
                'price' => 20000,
                'size' => '40-60 cm',
                'weight' => '0.4-0.8 kg',
                'age_months' => 6,
                'origin' => 'Deli, Indonesia',
                'tags' => ['Organic', 'Cocok Dataran Rendah'],
                'rating' => 4.6,
                'review_count' => 155,
                'sold_count' => 295,
            ],
            
            // Tanaman Kayu
            [
                'category_slug' => 'tanaman-kayu',
                'subcategory_slug' => 'jati-emas',
                'name' => 'Bibit Jati Emas',
                'scientific_name' => 'Tectona grandis',
                'description' => 'Bibit jati Emas unggulan untuk investasi jangka panjang. Pertumbuhan cepat, kayu berkualitas premium, nilai jual tinggi.',
                'care_instructions' => '1. Tanam di lokasi terbuka\n2. Sinar matahari penuh\n3. Siram saat muda\n4. Tahan kekeringan setelah dewasa\n5. Jarak tanam 5x5 meter',
                'price' => 15000,
                'size' => '40-70 cm',
                'weight' => '0.4-0.9 kg',
                'age_months' => 6,
                'origin' => 'Indonesia',
                'tags' => ['Cocok Dataran Rendah', 'Organic'],
                'rating' => 4.7,
                'review_count' => 125,
                'sold_count' => 280,
            ],
            [
                'category_slug' => 'tanaman-kayu',
                'subcategory_slug' => 'mahoni',
                'name' => 'Bibit Mahoni',
                'scientific_name' => 'Swietenia macrophylla',
                'description' => 'Bibit mahoni untuk penghijauan dan investasi kayu. Pertumbuhan cepat, kayu kuat dan tahan lama, cocok untuk furniture premium.',
                'care_instructions' => '1. Tanam di lokasi terbuka\n2. Tahan berbagai kondisi tanah\n3. Siram saat muda\n4. Minimal perawatan\n5. Jarak tanam 4x4 meter',
                'price' => 12000,
                'size' => '35-60 cm',
                'weight' => '0.3-0.7 kg',
                'age_months' => 5,
                'origin' => 'Amerika Tengah',
                'tags' => ['Cocok Dataran Rendah'],
                'rating' => 4.5,
                'review_count' => 95,
                'sold_count' => 220,
            ],
            [
                'category_slug' => 'tanaman-kayu',
                'subcategory_slug' => 'sengon-laut',
                'name' => 'Bibit Sengon Laut',
                'scientific_name' => 'Paraserianthes falcataria',
                'description' => 'Bibit sengon laut untuk usaha kayu jangka pendek. Pertumbuhan sangat cepat, siap panen dalam 5-7 tahun, nilai ekonomis tinggi.',
                'care_instructions' => '1. Tanam di lokasi dengan curah hujan tinggi\n2. Sinar matahari penuh\n3. Media tanam gembur\n4. Siram teratur saat muda\n5. Jarak tanam 3x3 meter',
                'price' => 8000,
                'size' => '30-50 cm',
                'weight' => '0.2-0.5 kg',
                'age_months' => 4,
                'origin' => 'Papua Nugini',
                'tags' => ['Cocok Dataran Rendah', 'Cepat Berbuah'],
                'rating' => 4.6,
                'review_count' => 140,
                'sold_count' => 380,
            ],
            
            // Sayuran
            [
                'category_slug' => 'sayuran',
                'subcategory_slug' => 'lombok',
                'name' => 'Bibit Lombok Besar',
                'scientific_name' => 'Capsicum annuum',
                'description' => 'Bibit lombok besar unggulan untuk hasil panen melimpah. Tumbuh cepat, buah besar dan pedas, cocok untuk kebutuhan dapur dan komersial.',
                'care_instructions' => '1. Tanam di lokasi dengan sinar matahari penuh\n2. Media tanam yang gembur dan subur\n3. Siram secara teratur jangan sampai kering\n4. Pupuk NPK setiap 2 minggu\n5. Jaga kelembaban tanah',
                'price' => 8000,
                'size' => '25-35 cm',
                'weight' => '0.15-0.25 kg',
                'age_months' => 3,
                'origin' => 'Indonesia',
                'tags' => ['Cepat Panen', 'Best Seller', 'Organic'],
                'is_bestseller' => true,
                'rating' => 4.8,
                'review_count' => 280,
                'sold_count' => 650,
            ],
            [
                'category_slug' => 'sayuran',
                'subcategory_slug' => 'terong',
                'name' => 'Bibit Terong Ungu',
                'scientific_name' => 'Solanum melongena',
                'description' => 'Bibit terong ungu premium dengan hasil buah lebat dan berkualitas. Daging tebal, tekstur lembut, cocok untuk berbagai masakan.',
                'care_instructions' => '1. Tanam di lokasi dengan sinar matahari minimal 6 jam\n2. Media tanam yang kaya humus\n3. Siram secara teratur pagi dan sore\n4. Pupuk organic untuk hasil optimal\n5. Staking saat tanaman mulai berbuah',
                'price' => 7000,
                'size' => '20-30 cm',
                'weight' => '0.1-0.2 kg',
                'age_months' => 2,
                'origin' => 'Indonesia',
                'tags' => ['Cepat Panen', 'Organic'],
                'rating' => 4.7,
                'review_count' => 210,
                'sold_count' => 480,
            ],
            [
                'category_slug' => 'sayuran',
                'subcategory_slug' => 'tomat',
                'name' => 'Bibit Tomat Cherry',
                'scientific_name' => 'Solanum lycopersicum',
                'description' => 'Bibit tomat cherry manis dan juicy. Buah kecil-kecil berwarna merah cerah, sangat cocok untuk salad dan camilan sehat.',
                'care_instructions' => '1. Tanam di lokasi dengan sinar matahari penuh\n2. Media tanam yang gembur dan drainase baik\n3. Siram secara teratur\n4. Pupuk kandang saat tanam\n5. Pangkas tunas liar untuk hasil maksimal',
                'price' => 9000,
                'size' => '25-35 cm',
                'weight' => '0.12-0.22 kg',
                'age_months' => 3,
                'origin' => 'Indonesia',
                'tags' => ['Cepat Panen', 'Premium'],
                'rating' => 4.9,
                'review_count' => 190,
                'sold_count' => 520,
            ],
        ];

        $tagIds = Tag::pluck('id', 'name');

        foreach ($products as $productData) {
            $tags = $productData['tags'] ?? [];
            unset($productData['tags']);
            
            $categorySlug = $productData['category_slug'];
            $subcategorySlug = $productData['subcategory_slug'];
            unset($productData['category_slug'], $productData['subcategory_slug']);
            
            $category = Category::where('slug', $categorySlug)->first();
            $subcategory = Subcategory::where('slug', $subcategorySlug)->first();
            
            if ($category && $subcategory) {
                $slug = \Illuminate\Support\Str::slug($productData['name']);
                $productData['category_id'] = $category->id;
                $productData['subcategory_id'] = $subcategory->id;
                $productData['slug'] = $slug;
                $productData['main_image'] = 'products/' . $slug . '.jpg';
                $productData['gallery_images'] = [
                    'products/' . $slug . '-1.jpg',
                    'products/' . $slug . '-2.jpg',
                ];
                $productData['stock'] = rand(50, 500);

                $product = Product::create($productData);
                
                // Attach tags
                $tagIdsToAttach = [];
                foreach ($tags as $tagName) {
                    if (isset($tagIds[$tagName])) {
                        $tagIdsToAttach[] = $tagIds[$tagName];
                    }
                }
                $product->tags()->attach($tagIdsToAttach);
            }
        }
    }
}
